#!/bin/bash
set -e

cd $(dirname $0)

export CLUSTER_NAME="backup-restore-operator"

./build
./test
./validate
./validate-ci
./package
./chart/test
./hull
# integration tests
./cleanup-cluster.sh
./setup-cluster.sh
./integration
